/** All user-facing Hebrew strings. Do not hard-code UI text anywhere else. */

const plural = (n: number, one: string, two: string, many: string) =>
  n === 1 ? one : n === 2 ? two : many.replace("{n}", String(n));

/** Prefix letters (כ, ו, ב…) take a hyphen only before digits: "כ-3 שנים" but "כשנתיים". */
const hePrefix = (letter: string, text: string) =>
  /^[\u2066-\u2068]?\d/.test(text) ? `${letter}-${text}` : `${letter}${text}`;

export const he = {
  app: {
    name: "אוטוסקופ",
    tagline: "בדיקת רכב יד שנייה לפי נתונים רשמיים",
    skipToContent: "דלגו לתוכן הראשי",
    home: "חזרה לעמוד הבית",
    backToTop: "חזרה לראש הדף",
  },

  theme: {
    toLight: "מעבר למצב בהיר",
    toDark: "מעבר למצב כהה",
  },

  search: {
    eyebrow: "נתונים רשמיים ממאגרי data.gov.il",
    titleTop: "קונים רכב יד שנייה?",
    titleBottom: "בדקו אותו לפני שסוגרים עסקה",
    subtitle:
      "הזינו מספר רישוי וקבלו תמונה מלאה: סטטוס הרכב, טסט, ריקולים פתוחים, היסטוריית בעלויות, הערכת שווי ומפרט טכני.",
    label: "מספר רישוי",
    placeholder: "12-345-67",
    submit: "בדיקת רכב",
    submitting: "מאתר במאגר...",
    newSearch: "חיפוש חדש",
    anotherTitle: "בודקים עוד רכב?",
    anotherText: "הזינו מספר רישוי נוסף כדי לבדוק אותו או להשוות בין הרכבים.",
    example: "לדוגמה:",
    shortcutHint: "טיפ: הקישו / כדי לחזור לשדה החיפוש",
    invalid: "יש להזין מספר רישוי של 5 עד 8 ספרות (מותר להקליד עם מקפים או רווחים).",
    empty: "יש להזין מספר רישוי.",
    recentTitle: "חיפושים אחרונים",
    recentClear: "ניקוי",
    recentClearAria: "ניקוי היסטוריית החיפושים",
    recentNote: "נשמר רק בדפדפן הזה ולא נשלח לשרת.",
    features: [
      { title: "סטטוס וטסט", text: "פעיל, מבוטל או לא פעיל — ותוקף הטסט" },
      { title: "דגלים אדומים", text: "שינוי מבנה, שינוי צבע, ריבוי בעלים וריקולים" },
      { title: "כמה הוא שווה", text: "מחירון, התאמת ערך ומה השפיע עליה" },
    ],
  },

  states: {
    loading: "טוען את נתוני הרכב מהמאגרים הממשלתיים...",
    notFoundTitle: (plate: string) => `לא נמצא רכב עם המספר ${plate}`,
    notFoundText: "לא מצאנו את המספר באף אחד ממאגרי הרישוי. כדאי לבדוק:",
    notFoundTips: [
      "שהמספר הוקלד נכון — 7 או 8 ספרות ברוב הרכבים.",
      "שלא התחלפו ספרות (למשל 6 ו-8, או 1 ו-7).",
      "רכבים ישנים מאוד, רכבי צבא או רכבים זרים עשויים שלא להופיע במאגר.",
    ],
    tryAnother: "חיפוש מספר אחר",
    upstreamTitle: "מאגר הנתונים הממשלתי אינו זמין כרגע",
    upstreamText: "התקשורת עם data.gov.il נכשלה. זו בדרך כלל תקלה זמנית — נסו שוב בעוד רגע.",
    networkTitle: "אין חיבור לשרת",
    networkText: "לא הצלחנו להתחבר לשירות. בדקו את החיבור לאינטרנט ונסו שוב.",
    genericTitle: "משהו השתבש",
    genericText: "הבקשה נכשלה. נסו שוב בעוד רגע.",
    retry: "נסו שוב",
    technicalDetails: "פרטים טכניים",
    cachedBadge: "נתונים שמורים",
    cachedText: "אין כרגע חיבור לשירות, ולכן מוצגים הנתונים האחרונים שנשמרו בזיכרון במהלך הביקור.",
    partialTitle: "נמצא רק ברשימת ההנחה לבטיחות",
    partialText:
      "המספר מופיע ברשימת כלי הרכב הזכאים להנחה לאחר התקנת מערכות בטיחות, אך אין עבורו נתוני רישום מלאים במאגר.",
  },

  nav: {
    label: "ניווט מהיר בדף",
    summary: "סיכום",
    value: "שווי",
    history: "היסטוריה",
    energy: "עלות אנרגיה",
    specs: "מפרט",
  },

  hero: {
    eyebrow: "תוצאת בדיקה",
    plateAria: (plate: string) => `לוחית רישוי ${plate}`,
    copyPlate: "העתקת מספר הרכב",
    copyLink: "העתקת קישור",
    print: "הדפסה / PDF",
    compare: "הוספה להשוואה",
    inCompare: "בהשוואה · לצפייה",
    fallbackTitle: "רכב",
    year: (y: string) => `שנת ${y}`,
  },

  toast: {
    copied: "הועתק ללוח",
    linkCopied: "הקישור הועתק — הוא כולל רק את מספר הרכב",
    copyFailed: "ההעתקה נכשלה",
    compareAdded: (count: number, limit: number) => `הרכב נוסף להשוואה (${count} מתוך ${limit})`,
    compareFull: "אפשר להשוות עד 3 רכבים. הסירו רכב כדי להוסיף חדש.",
    viewCompare: "לצפייה בהשוואה",
  },

  status: {
    cancelledTitle: "הרכב בוטל סופית",
    cancelledSince: (date: string) => `בוטל בתאריך ${date}`,
    cancelledNoDate: "הרכב ירד מהכביש לצמיתות",
    ribbon: "רכב מבוטל — נתוני היסטוריה בלבד",
    inactiveTitle: "הרכב אינו פעיל",
    inactiveText: "הרכב מופיע במאגר כלי הרכב הלא פעילים",
    testExpiredTitle: (days: number) =>
      days === 0 ? "הטסט פג היום" : `הטסט פג לפני ${plural(days, "יום אחד", "יומיים", "{n} ימים")}`,
    testExpiredText: (date: string) => `תוקף הטסט הסתיים ב-${date}`,
    testSoonTitle: (days: number) =>
      days === 0 ? "הטסט פג היום" : `הטסט יפוג בעוד ${plural(days, "יום אחד", "יומיים", "{n} ימים")}`,
    testSoonText: (date: string) => `בתוקף עד ${date}`,
    recallTitle: (n: number) => (n === 1 ? "ריקול אחד שלא בוצע" : `${n} ריקולים שלא בוצעו`),
    recallText: "לחצו לפרטים על הריקולים הפתוחים",
    okTitle: "הרכב פעיל",
    okTestUntil: (date: string) => `טסט בתוקף עד ${date}`,
    okNoTest: "אין במאגר מידע על תוקף הטסט",
    alertsLabel: "התראות נוספות",
    grayedCancelled: "הרכב בוטל סופית — נתון זה אינו רלוונטי לרכישה.",
    grayedInactive: "הרכב אינו פעיל — נתון זה אינו רלוונטי לרכישה.",
  },

  summary: {
    title: "סיכום לקונה",
    subtitle: "מה חשוב לדעת לפני שקונים",
    verdictOk: "נראה תקין",
    verdictWarn: "כדאי לבדוק לפני קנייה",
    verdictBad: "סיכון גבוה",
    verdictOkText: "לא נמצאו דגלים אדומים בנתונים הרשמיים.",
    verdictWarnText: "נמצאו נקודות שכדאי לברר מול המוכר ובבדיקה מקצועית.",
    verdictBadText: "נמצאו ממצאים מהותיים. מומלץ לשקול היטב לפני רכישה.",
    disclaimer:
      "הנתונים מבוססים על מאגרי data.gov.il ואינם תחליף לבדיקה מקצועית במכון בדיקה.",
    levelOk: "תקין",
    levelWarn: "לתשומת לב",
    levelBad: "חמור",
    levelInfo: "מידע",
    flags: {
      cancelled: "הרכב בוטל סופית",
      inactive: "הרכב מסומן במאגר כלא פעיל",
      recalls: (n: number) => (n === 1 ? "ריקול אחד שלא בוצע" : `${n} ריקולים שלא בוצעו`),
      noRecalls: "לא נמצאו ריקולים פתוחים",
      lpg: "הותקנה ברכב מערכת גפ״מ — נסיעה גם על גז בנוסף לבנזין",
      structure: "תועד שינוי מבנה",
      color: "תועד שינוי צבע",
      tires: "תועדה החלפת צמיגים לסוג שונה",
      noTechnical: "אין במאגר נתוני היסטוריה טכנית",
      owners: (n: number) => `${plural(n, "בעלים אחד", "2 בעלים", "{n} בעלים")} לאורך חיי הרכב`,
      nonPrivate: (types: string) => `היסטוריית בעלות לא פרטית: ${types}`,
      privateOnly: "כל הבעלויות הרשומות פרטיות",
      highKm: (perYear: string) => `קילומטראז' גבוה ביחס לגיל — כ-${perYear} ק״מ לשנה`,
      lowKm: (perYear: string) => `קילומטראז' נמוך במיוחד — כ-${perYear} ק״מ לשנה. כדאי לוודא`,
      normalKm: (perYear: string) => `קילומטראז' סביר — כ-${perYear} ק״מ לשנה`,
      testExpired: "הטסט פג תוקף",
      testValid: (date: string) => `טסט בתוקף עד ${date}`,
      testSoon: (days: number) => `הטסט יפוג בעוד ${plural(days, "יום אחד", "יומיים", "{n} ימים")}`,
    },
    miniValueTitle: "הערכת שווי",
    miniValueLink: "לפירוט המלא",
  },

  value: {
    title: "כמה הרכב שווה?",
    subtitle: "מחיר מחירון, התאמת ערך ומה השפיע עליה",
    estimateOnly: "הערכה בלבד",
    estimatedValue: "ערך משוערך",
    listPrice: "מחיר מחירון",
    totalChange: "סה״כ שינוי ערך",
    noPrice: "לא נמצא מחירון לדגם, מוצגים אחוזי שינוי בלבד",
    notPurchasePrice: "הערכה בלבד — אינה מחיר רכישה מומלץ.",
    factorsTitle: "גורמים שהשפיעו על הערך",
    biggestImpact: "ההשפעה הגדולה ביותר",
    raises: "מעלה את הערך",
    lowers: "מוריד את הערך",
    neutral: "ללא השפעה",
    chartTitle: "מהמחירון לערך המשוערך",
    chartAxisNote: "הציר אינו מתחיל באפס כדי להמחיש את השינויים",
    chartStart: "מחירון",
    chartEnd: "משוערך",
    basisTitle: "בסיס החישוב",
    basis: {
      age: "גיל הרכב",
      km: "קילומטראז'",
      owners: "מספר בעלים",
      vehicleCategory: "קטגוריית רכב",
      ownerCategory: "קטגוריית בעלות",
      originality: "מקוריות",
      ownershipType: "סוג בעלות לחישוב",
    },
    perYear: (v: string) => `ממוצע ${v} ק״מ לשנה`,
    explainButton: "מה זה אומר?",
    explainTitle: "איך מחושבת הערכת השווי?",
    explainBody: [
      "נקודת המוצא היא מחיר המחירון של הדגם ושנת הייצור, כפי שמופיע במאגר היבואנים.",
      "קילומטראז': נסועה גבוהה מהמקובל לגיל הרכב מורידה מהערך, ונסועה נמוכה עשויה להעלות אותו.",
      "מספר בעלים: כל בעלים נוסף מוריד מהערך.",
      "סוג בעלות: נבחרת הבעלות ה\"גרועה\" ביותר מבין כל הבעלים ונתון המקוריות (למשל השכרה, מונית או חברה).",
      "התוצאה היא הערכה סטטיסטית בלבד. מצב מכני, אבזור, תחזוקה וביקוש בשוק אינם נלקחים בחשבון — ולכן אין להציגה כמחיר רכישה מומלץ.",
    ],
  },

  energy: {
    title: "עלות צריכת אנרגיה חודשית",
    subtitle: "הערכה לפי נסועה חודשית, צריכה ומחירי אנרגיה משוערים",
    estimateOnly: "הערכה בלבד",
    kmLabel: "נסועה חודשית משוערת",
    fuelConsumption: "צריכת דלק",
    fuelPrice: "מחיר דלק",
    electricConsumption: "צריכת חשמל",
    electricPrice: "מחיר חשמל",
    monthlyCost: "עלות חודשית משוערת",
    cannotCalculate: "לא ניתן לחשב",
    kmPerLiter: "ק״מ לליטר",
    perLiter: "לליטר",
    kwhPer100Km: "kWh / 100 km",
    perKwh: "/ kWh",
    noteFuel: "* החישוב משוער ותלוי בנסועה, בצריכת הרכב ובמחירי האנרגיה.",
    noteElectric: "* החישוב משוער ותלוי בנסועה, בצריכת הרכב ובמחיר החשמל.",
    noteUnknown: "* נתוני צריכת האנרגיה אינם זמינים עבור סוג רכב זה.",
    defaultsNote: "הצריכה והמחירים הם ערכי ברירת מחדל של המערכת ואינם נתוני הדגם.",
    error: "חישוב העלות נכשל.",
  },

  history: {
    title: "היסטוריה",
    subtitle: "אירועים מתועדים ובעלויות לאורך חיי הרכב",
    flagsTitle: "אירועים במאגר",
    lpg: "מערכת גפ״מ",
    lpgInstalled: "הותקנה / שונתה",
    lpgNote: "נסיעה גם על גז (LPG) בנוסף לבנזין. אינה משפיעה על ערך הרכב.",
    flags: {
      structure: "שינוי מבנה",
      color: "שינוי צבע",
      tires: "שינוי צמיגים",
    },
    documented: "תועד במאגר",
    notDocumented: "לא תועד",
    unknown: "לא ידוע",
    flagsNote: "היעדר רישום במאגר אינו הוכחה שהאירוע לא קרה.",
    timelineTitle: "ציר בעלויות",
    owners: (n: number) => plural(n, "בעלים אחד", "2 בעלים", "{n} בעלים"),
    nonPrivateCount: (n: number) => (n === 1 ? "בעלות לא פרטית אחת" : `${n} בעלויות לא פרטיות`),
    current: "בעלות נוכחית",
    duration: (text: string) => `משך: ${text}`,
    unknownDate: "תאריך לא ידוע",
    firstRegistration: "רישום ראשון",
    carAge: (duration: string) => `גיל הרכב: ${duration}`,
    originality: "מקוריות",
    odometer: "קילומטראז' בטסט אחרון",
    odometerAvg: (perYear: string) => `ממוצע ${perYear} ק״מ לשנה`,
    odometerVsNational: (avg: string) => `ממוצע ארצי: כ-${avg} ק״מ לשנה`,
    aboveAvg: "מעל הממוצע",
    belowAvg: "מתחת לממוצע",
    nearAvg: "סביב הממוצע",
    noHistory: "אין במאגר נתוני היסטוריה לרכב זה.",
  },

  recalls: {
    title: (n: number) =>
      n === 1 ? "ריקול אחד שלא בוצע — חשוב לפני קנייה" : `${n} ריקולים שלא בוצעו — חשוב לפני קנייה`,
    note: "מומלץ לוודא מול היבואן שהריקול בוצע או יבוצע ללא עלות.",
    recallType: "סוג ריקול",
    faultType: "סוג תקלה",
    faultDescription: "תיאור תקלה",
    openedDate: "תאריך פתיחה",
    recallId: "מזהה ריקול",
  },

  accordion: {
    openAll: "פתיחת הכל",
    closeAll: "סגירת הכל",
    count: (n: number) => (n === 1 ? "נתון אחד" : `${n} נתונים`),
    sectionTitle: "מפרט ונתונים מלאים",
    sectionSubtitle: "כל הנתונים שקיימים במאגר — מוצגים רק שדות עם ערך",
    groups: {
      identity: "זהות הרכב",
      test: "טסט ורישוי",
      engine: "מנוע, דלק ומשקל",
      recalls: "ריקולים",
      safety: "בטיחות",
      comfort: "אבזור ונוחות",
      pollution: "זיהום ופליטות",
      dimensions: "מידות וגרירה",
      colorTires: "צבע וצמיגים",
      approvals: "תקינה ואגרות",
      priceList: "מחירון הדגם",
    },
    more: "עוד",
    less: "פחות",
    copy: "העתקה",
    copyAria: (label: string) => `העתקת ${label}`,
  },

  safety: {
    scaleTitle: "רמת אבזור בטיחותי",
    scaleValue: (v: number, max: number) => `רמה ${v} מתוך ${max}`,
    scaleLow: "בסיסי",
    scaleHigh: "מתקדם",
    present: "קיים בדגם",
    absent: "לא קיים בדגם",
    matrixTitle: "מערכות בטיחות",
  },

  pollution: {
    scaleTitle: "קבוצת זיהום",
    scaleLow: "נקי",
    scaleHigh: "מזהם",
    scaleValue: (v: number) => `קבוצה ${v} מתוך 15`,
    combined: "משולב",
    city: "עירוני",
    highway: "בינעירוני",
  },

  priceList: {
    loading: "טוען את מחירון הדגם...",
    empty: "לא נמצאו רשומות מחירון לדגם ולשנה.",
    error: "טעינת המחירון נכשלה.",
    importer: "יבואן",
    commercialName: "כינוי מסחרי",
    modelType: "סוג דגם",
    price: "מחיר",
    year: "שנה",
  },

  compare: {
    title: "השוואת רכבים",
    subtitle: "רק מה שחשוב לקונה רכב יד שנייה",
    close: "סגירת ההשוואה",
    addLabel: "הוספת רכב להשוואה",
    addButton: "הוספה",
    adding: "מאתר...",
    limit: "אפשר להשוות עד 3 רכבים.",
    remove: "הסרה",
    removeAria: (plate: string) => `הסרת רכב ${plate} מההשוואה`,
    clear: "ניקוי ההשוואה",
    onlyDiff: "הצגת הבדלים בלבד",
    empty: "הוסיפו לפחות שני רכבים כדי להשוות ביניהם.",
    emptyNone: "עדיין אין רכבים בהשוואה. הזינו מספר רישוי למעלה, או לחצו \"הוספה להשוואה\" בדף של רכב.",
    emptyOne: "יש רכב אחד בהשוואה. הוסיפו רכב נוסף כדי לראות את ההבדלים.",
    headerCount: "ההשוואה שלי",
    headerShort: "השוואה",
    headerEmptyHint: "אין עדיין רכבים בהשוואה. בדף רכב לחצו \"הוספה להשוואה\".",
    openCompare: "פתיחת ההשוואה",
    back: "חזרה",
    openVehicle: "מעבר לדף הרכב",
    myTitle: "ההשוואה שלי",
    myCount: (n: number, limit: number) => `${n} מתוך ${limit}`,
    myHintOne: "הוסיפו רכב נוסף כדי להשוות ביניהם.",
    myHintEmpty: "רוצים להשוות? בדף של כל רכב לחצו \"הוספה להשוואה\" — אפשר להשוות עד 3 רכבים.",
    duplicate: "הרכב כבר נמצא בהשוואה.",
    winnerAria: "עדיף בשורה זו",
    missing: "—",
    bestTitle: "הרכב הכי כדאי לפי הנתונים",
    bestNote: "המלצה כללית בלבד, על בסיס ניקוד פשוט ושקוף של הנתונים הרשמיים.",
    bestWhy: "למה?",
    points: (n: number) => `${n} נק׳`,
    noBest: "אין מספיק נתונים כדי להמליץ על רכב מסוים.",
    excluded: "לא נכלל בהמלצה — הרכב מבוטל או לא פעיל",
    sections: {
      status: "סטטוס",
      value: "שווי",
      age: "גיל וקילומטראז'",
      owners: "בעלויות",
      flags: "היסטוריה",
      origin: "מקור",
      safety: "בטיחות",
      cost: "עלויות אחזקה",
      spec: "מפרט בסיסי",
    },
    rows: {
      status: "סטטוס",
      testUntil: "טסט בתוקף עד",
      recalls: "ריקולים פתוחים",
      estimatedValue: "ערך משוערך",
      listPrice: "מחיר מחירון",
      depreciation: "שינוי ערך כולל",
      topFactor: "הגורם המשפיע ביותר",
      year: "שנת יצור",
      age: "גיל",
      km: "קילומטראז'",
      kmPerYear: "ממוצע לשנה",
      owners: "מספר בעלים",
      currentOwnership: "בעלות נוכחית",
      nonPrivate: "בעלויות לא פרטיות",
      lpg: "מערכת גפ״מ",
      structure: "שינוי מבנה",
      color: "שינוי צבע",
      tires: "שינוי צמיגים",
      originality: "מקוריות",
      importType: "סוג יבוא",
      safetyScore: "ניקוד בטיחות",
      safetyLevel: "רמת אבזור בטיחותי",
      abs: "ABS",
      airbags: "כריות אוויר",
      stability: "בקרת יציבות",
      emergencyBraking: "בלימת חירום",
      laneKeeping: "שמירה על נתיב",
      reverseCamera: "מצלמת רוורס",
      feeGroup: "קבוצת אגרה",
      estimatedLicenseFee: "אגרת רישוי שנתית (משוערת)",
      feeGroupPrice: "שווי שימוש חודשי (משוער)",
      energyCost: "עלות דלק / חשמל חודשית (משוערת)",
      warranty: "אחריות יצרן (משוערת)",
      pollutionGroup: "קבוצת זיהום",
      greenScore: "מדד ירוק",
      fuel: "סוג דלק",
      driveTechnology: "טכנולוגיית הנעה",
      displacement: "נפח מנוע",
      horsepower: "כוח סוס",
      transmission: "תיבת הילוכים",
      drive: "הנעה",
      seats: "מושבים",
      doors: "דלתות",
    },
    statusActive: "פעיל",
    statusCancelled: "מבוטל",
    statusInactive: "לא פעיל",
    automatic: "אוטומטית",
    manual: "ידנית",
    none: "אין",
    warrantyUntil: (month: string) => `בתוקף עד ${month}`,
    warrantyEnded: (month: string) => `הסתיימה ${hePrefix("ב", month)}`,
    warrantyActiveAria: "באחריות יצרן",
    insights: {
      licenseFee: (low: string, high: string, diff: string) =>
        `אגרת הרישוי של ${low} נמוכה ${hePrefix("ב", diff)} בשנה מזו של ${high}.`,
      licenseFeeSame: (fee: string) => `אגרת הרישוי זהה בכל הרכבים: ${fee} בשנה.`,
      usageValue: (low: string, high: string, diff: string, yearly: string) =>
        `שווי השימוש של ${low} נמוך ${hePrefix("ב", diff)} בחודש (${yearly} בשנה) מזה של ${high}. רלוונטי לרכב צמוד: שווי נמוך יותר = פחות מס הכנסה.`,
      usageValueSame: (value: string) => `שווי השימוש זהה בכל הרכבים: ${value} בחודש.`,
      energyCost: (low: string, high: string, diff: string, yearly: string, km: string) =>
        `עלות הדלק / החשמל של ${low} נמוכה ${hePrefix("ב", diff)} בחודש (${yearly} בשנה) מזו של ${high}, לפי ${km} בחודש.`,
      energyCostSame: (value: string, km: string) =>
        `עלות הדלק / החשמל זהה בכל הרכבים: ${value} בחודש, לפי ${km} בחודש.`,
      warrantyOnly: (name: string, left: string) => `רק ${name} עדיין באחריות יצרן, לעוד ${left}.`,
      warrantyLonger: (best: string, left: string, other: string, diff: string) =>
        `האחריות של ${best} נמשכת עוד ${left}, ${diff} יותר מזו של ${other}.`,
      warrantySame: "לרכבים שעדיין באחריות נותר בערך אותו זמן אחריות.",
      warrantyNone: "לאף אחד מהרכבים לא נותרה אחריות יצרן.",
      warrantyNote: "(הערכה: 3 שנים ממועד העלייה לכביש.)",
    },
    reasons: {
      status: "הרכב פעיל",
      recalls: "פחות ריקולים פתוחים",
      test: "טסט בתוקף לזמן ארוך יותר",
      depreciation: "ירידת ערך קטנה יותר",
      year: "שנתון חדש יותר",
      km: "קילומטראז' נמוך יותר",
      owners: "פחות בעלים",
      nonPrivate: "פחות בעלויות לא פרטיות",
      currentOwnership: "בעלות נוכחית פרטית",
      flags: "פחות אירועים מתועדים בהיסטוריה",
      safety: "בטיחות טובה יותר",
      pollution: "מזהם פחות",
      licenseFee: "אגרת רישוי נמוכה יותר",
      energyCost: "עלות דלק / חשמל נמוכה יותר",
      warranty: "יותר זמן באחריות יצרן",
    },
  },

  footer: {
    source: "מקור הנתונים: מאגרי המידע הפתוחים של ממשלת ישראל (data.gov.il)",
    updated: (date: string) => `עדכון אחרון של הרשומה: ${date}`,
    disclaimer:
      "המידע מוצג כפי שהוא מופיע במאגרים הממשלתיים ועשוי להיות חלקי או לא מעודכן. אין לראות בו ייעוץ או תחליף לבדיקה מקצועית.",
    privacy: "פרטיות",
    privacyText:
      "חיפושים אחרונים נשמרים רק בדפדפן שלכם. מספר השלדה ומספר המנוע אינם נשמרים בהיסטוריה ואינם נכללים בקישורי שיתוף.",
    printedAt: (date: string) => `הופק בתאריך ${date}`,
  },

  modal: {
    close: "סגירה",
  },

  common: {
    yes: "כן",
    no: "לא",
    unknown: "לא ידוע",
    years: (v: string) => `${v} שנים`,
    about: (text: string) => hePrefix("כ", text),
    and: (a: string, b: string) => `${a} ${hePrefix("ו", b)}`,
  },

  duration: {
    years: (n: number) => plural(n, "שנה", "שנתיים", "{n} שנים"),
    months: (n: number) => plural(n, "חודש", "חודשיים", "{n} חודשים"),
    lessThanMonth: "פחות מחודש",
  },

  days: (n: number) => plural(n, "יום אחד", "יומיים", "{n} ימים"),

  warranty: {
    active: "בתוקף",
    expired: "הסתיימה",
  },

  units: {
    km: "ק״מ",
    kg: "ק״ג",
    cc: "סמ״ק",
    hp: "כ״ס",
    gPerKm: "גר׳/ק״מ",
    volt: "וולט",
  },

  ownership: {
    private: "פרטי",
    commercial: "מסחרי",
    rental: "השכרה / ליסינג",
    taxi: "מונית",
    government: "ממשלתי",
    public: "ציבורי",
    kibbutz: "קיבוץ",
    other: "אחר",
  },

  enums: {
    vehicleCategory: {
      Private: "פרטי",
      Commercial4t: "מסחרי עד 4 טון",
      Commercial: "מסחרי",
      Taxi: "מונית",
      Minibus: "מיניבוס",
    } as Record<string, string>,
    ownerCategory: {
      Private: "פרטי",
      Commercial: "מסחרי",
      Public: "ציבורי",
      Rental: "השכרה/ליסינג",
      Kibbutz: "קיבוץ",
      Government: "ממשלתי",
      Taxi: "מונית",
      DriveTech: "דרייב-טק",
    } as Record<string, string>,
    factor: {
      Kilometers: "קילומטראז'",
      OwnerCount: "מספר בעלים",
      OwnershipType: "סוג בעלות",
    } as Record<string, string>,
  },

  /** Field labels, keyed by DTO property name. */
  labels: {
    registrationNumber: "מספר רכב",
    id: "מזהה",
    chassisNumber: "מספר שילדה (VIN)",
    engineNumber: "מספר מנוע",
    commercialName: "כינוי מסחרי",
    manufacturerName: "תוצר",
    manufacturerCode: "קוד תוצר",
    manufacturerCountryName: "ארץ תוצר",
    tozar: "תוצר (קטלוג)",
    modelName: "דגם",
    modelCode: "קוד דגם",
    modelType: "סוג דגם",
    modelYear: "שנת דגם",
    trimLevel: "רמת גימור",
    vehicleTypeName: "סוג רכב",
    vehicleTypeCode: "קוד סוג רכב",
    manufactureYear: "שנת יצור",
    importType: "סוג יבוא",
    engineManufacturer: "תוצר מנוע",
    engineModel: "דגם מנוע",
    fuelType: "סוג דלק",
    fuelName: "סוג דלק (קטלוג)",
    fuelCode: "קוד דלק",
    totalWeight: "משקל כולל",
    curbWeight: "משקל עצמי",
    liftingLoadWeight: "משקל מטען הרמה",
    color: "צבע רכב",
    colorCode: "קוד צבע",
    frontTire: "צמיג קדמי",
    rearTire: "צמיג אחורי",
    lastTestDate: "תאריך מבחן אחרון",
    testValidUntil: "תוקף טסט",
    roadEntryDate: "מועד עלייה לכביש",
    estimatedWarrantyEndDate: "אחריות יצרן משוערת עד",
    registrationOrder: "הוראת רישום",
    ownershipType: "בעלות נוכחית",
    updatedDate: "תאריך עדכון",
    cancellationDate: "תאריך ביטול",
    safetyEquipmentLevel: "רמת אבזור בטיחותי",
    pollutionGroup: "קבוצת זיהום",
    horsepower: "כוח סוס",
    engineDisplacement: "נפח מנוע",
    driveName: "הנעה",
    driveCode: "קוד הנעה",
    driveTechnologyName: "טכנולוגיית הנעה",
    driveTechnologyCode: "קוד טכנולוגיית הנעה",
    automaticTransmissionIndicator: "תיבת הילוכים אוטומטית",
    bodyType: "מרכב",
    doorCount: "מספר דלתות",
    seatCount: "מספר מושבים",
    height: "גובה",
    towingCapacityWithBrakes: "כושר גרירה עם בלמים",
    towingCapacityWithoutBrakes: "כושר גרירה בלי בלמים",
    airConditioningIndicator: "מזגן",
    powerSteeringIndicator: "הגה כוח",
    powerWindowsSource: "חלונות חשמל (מקור)",
    powerWindowCount: "מספר חלונות חשמל",
    powerSunroofIndicator: "חלון בגג",
    alloyWheelsIndicator: "גלגלי סגסוגת קלה",
    cargoBoxIndicator: "ארגז",
    safetyScore: "ניקוד בטיחות",
    absIndicator: "ABS",
    airbagCount: "מספר כריות אוויר",
    airbagsSource: "כריות אוויר (מקור)",
    stabilityControlIndicator: "בקרת יציבות",
    laneDepartureControlIndicator: "בקרת סטייה מנתיב",
    forwardDistanceMonitoringIndicator: "ניטור מרחק מלפנים",
    blindSpotDetectionIndicator: "זיהוי בשטח מת",
    adaptiveCruiseControlIndicator: "בקרת שיוט אדפטיבית",
    pedestrianDetectionIndicator: "זיהוי הולכי רגל",
    brakeAssistIndicator: "מערכת עזר לבלימה",
    reverseCameraIndicator: "מצלמת רוורס",
    tirePressureMonitoringIndicator: "חיישני לחץ אוויר בצמיגים",
    seatbeltReminderIndicator: "חיישני חגורות בטיחות",
    automaticLightingForwardTravelIndicator: "תאורה אוטומטית בנסיעה קדימה",
    automaticHighBeamControlIndicator: "שליטה אוטומטית באורות גבוהים",
    dangerousApproachDetectionIndicator: "זיהוי התקרבות מסוכנת",
    trafficSignRecognitionIndicator: "זיהוי תמרורי תנועה",
    twoWheeledVehicleDetection: "זיהוי רכב דו-גלגלי",
    activeLaneControl: "בקרת נתיב אקטיבית",
    automaticBrakingReverseTravel: "בלימה אוטומטית בנסיעה לאחור",
    speedControlIsa: "בקרת מהירות ISA",
    emergencyBrakingPedestriansCyclists: "בלימת חירום להולכי רגל ורוכבי אופניים",
    sideCollisionBlindSpot: "התרעת התנגשות צד בשטח מת",
    alcoLock: "אלכו-לוק",
    greenScore: "מדד ירוק",
    co2Amount: "CO₂ (משולב)",
    noxAmount: "NOx (משולב)",
    pm10Amount: "PM10 (משולב)",
    hcAmount: "HC (משולב)",
    hcNoxAmount: "HC+NOx",
    coAmount: "CO (משולב)",
    co2AmountCity: "CO₂ עירוני",
    noxAmountCity: "NOx עירוני",
    pm10AmountCity: "PM10 עירוני",
    hcAmountCity: "HC עירוני",
    coAmountCity: "CO עירוני",
    co2AmountHighway: "CO₂ בינעירוני",
    noxAmountHighway: "NOx בינעירוני",
    pm10AmountHighway: "PM10 בינעירוני",
    hcAmountHighway: "HC בינעירוני",
    coAmountHighway: "CO בינעירוני",
    co2Wltp: "CO₂ WLTP",
    hcWltp: "HC WLTP",
    pmWltp: "PM WLTP",
    noxWltp: "NOx WLTP",
    coWltp: "CO WLTP",
    co2WltpNedc: "CO₂ WLTP-NEDC",
    feeGroupCode: "קבוצת אגרה",
    estimatedLicenseFee: "אגרת רישוי משוערת",
    feeGroupPrice: "שווי שימוש חודשי (משוער)",
    homologationTypeName: "סוג תקינה",
    homologationTypeCode: "קוד סוג תקינה",
    euTypeApproval: "אישור תקינה EU",
    converterTypeName: "סוג ממיר",
    converterTypeCode: "קוד סוג ממיר",
    batteryVoltageDg: "דרגת מתח סוללה",
    laneDepartureControlRegulationSource: "מקור התקנה — בקרת סטייה מנתיב",
    forwardDistanceMonitoringRegulationSource: "מקור התקנה — ניטור מרחק מלפנים",
    pedestrianDetectionRegulationSource: "מקור התקנה — זיהוי הולכי רגל",
    automaticHighBeamControlRegulationSource: "מקור התקנה — אורות גבוהים אוטומטיים",
    trafficSignRecognitionRegulationSource: "מקור התקנה — זיהוי תמרורים",
    modelId: "מזהה רשומת דגם",
    technicalId: "מזהה רשומה טכנית",
  } as Record<string, string>,
};

export type Strings = typeof he;
